'use client';

import { useMemo } from 'react';
import type { StoryMessageData } from './StoryMessage';

interface BranchNode {
  id: number;
  type: 'narration' | 'choice';
  content: string;
  selected?: boolean;
  children: BranchNode[];
  messageIndex: number;
}

interface RawStoryRow {
  role?: string;
  content?: string;
  narrative?: string;
  dialogues?: { character?: string; content?: string }[];
  choices?: string[];
  metadata?: string | Record<string, unknown>;
}

interface StoryBranchProps {
  messages: StoryMessageData[];
  rawMessages: RawStoryRow[];
  onNodeClick?: (messageIndex: number) => void;
}

function buildTree(messages: StoryMessageData[], rawMessages: RawStoryRow[]): BranchNode[] {
  const nodes: BranchNode[] = [];
  let nodeId = 0;

  for (let i = 0; i < messages.length; i++) {
    const msg = messages[i];

    if (msg.role === 'narrator') {
      nodes.push({
        id: nodeId++,
        type: 'narration',
        content: msg.content,
        messageIndex: i,
        children: [],
      });
    }

    if (msg.role === 'character') {
      nodes.push({
        id: nodeId++,
        type: 'narration',
        content: msg.characterName ? `${msg.characterName}：${msg.content}` : msg.content,
        messageIndex: i,
        children: [],
      });
    }

    if (msg.role === 'player') {
      // Find the previous AI message's choices from rawMessages
      const availableChoices = findChoicesBeforePlayer(rawMessages, i);
      const selectedText = msg.content;

      const branchNode: BranchNode = {
        id: nodeId++,
        type: 'choice',
        content: selectedText,
        selected: true,
        messageIndex: i,
        children: [],
      };

      // Add unexplored branches
      if (availableChoices.length > 0) {
        const unexplored = availableChoices.filter(c => c !== selectedText);
        for (const uc of unexplored) {
          branchNode.children.push({
            id: nodeId++,
            type: 'choice',
            content: uc,
            selected: false,
            messageIndex: -1,
            children: [],
          });
        }
      }

      nodes.push(branchNode);
    }
  }

  return nodes;
}

function findChoicesBeforePlayer(rawMessages: RawStoryRow[], playerDisplayIndex: number): string[] {
  // Walk raw messages to find the choices array from the AI message preceding this player message

  // Find the matching player message in raw messages
  for (let i = 0; i < rawMessages.length; i++) {
    const rm = rawMessages[i];
    if (rm.role === 'player' || rm.role === 'user') {
      if (isMatchingPlayerMessage(rawMessages, i, playerDisplayIndex)) {
        for (let j = i - 1; j >= 0; j--) {
          const prev = rawMessages[j];
          if (prev.role !== 'player' && prev.role !== 'user') {
            const choices = extractChoices(prev);
            if (choices.length > 0) return choices;
          }
        }
        break;
      }
    }
  }

  return [];
}

function isMatchingPlayerMessage(rawMessages: RawStoryRow[], rawIndex: number, displayIndex: number): boolean {
  // Count display messages generated by raw messages up to rawIndex
  let displayCount = 0;
  for (let i = 0; i < rawMessages.length; i++) {
    const rm = rawMessages[i];
    if (i === rawIndex) {
      return displayCount === displayIndex;
    }
    if (rm.role === 'player' || rm.role === 'user') {
      displayCount++;
    } else {
      const content = rm.content || '';
      let parsed: Record<string, unknown> | null = null;
      try {
        parsed = typeof content === 'string' ? JSON.parse(content) : content
      } catch {
        /* non-JSON narrative content is expected */
      }

      if (rm.narrative || rm.dialogues) {
        if (rm.narrative) displayCount++;
        if (Array.isArray(rm.dialogues)) displayCount += rm.dialogues.length;
      } else if (parsed && typeof parsed === 'object' && (parsed.narration || parsed.narrative || parsed.dialogue || parsed.dialogues)) {
        if (parsed.narration || parsed.narrative) displayCount++;
        const dlg = parsed.dialogue || parsed.dialogues;
        if (Array.isArray(dlg)) displayCount += dlg.length;
      } else if (content) {
        displayCount++;
      }
    }
  }
  return false;
}

function extractChoices(msg: RawStoryRow): string[] {
  if (msg.choices && Array.isArray(msg.choices)) return msg.choices;

  const content = msg.content || '';
  let parsed: unknown = null;
  try {
    parsed = typeof content === 'string' ? JSON.parse(content) : content;
  } catch {
    /* non-JSON narrative content is expected */
  }

  if (parsed && typeof parsed === 'object' && parsed !== null && 'choices' in parsed && Array.isArray((parsed as { choices: unknown }).choices)) {
    return (parsed as { choices: string[] }).choices;
  }

  const metadata = msg.metadata;
  if (metadata) {
    try {
      const meta: unknown = typeof metadata === 'string' ? JSON.parse(metadata) : metadata;
      if (
        meta &&
        typeof meta === 'object' &&
        meta !== null &&
        'choices' in meta &&
        Array.isArray((meta as { choices: unknown }).choices)
      ) {
        return (meta as { choices: string[] }).choices;
      }
    } catch {
      // Invalid metadata JSON — ignore
    }
  }

  return [];
}

function truncate(text: string, max: number = 30): string {
  if (text.length <= max) return text;
  return text.slice(0, max) + '...';
}

export function StoryBranch({ messages, rawMessages, onNodeClick }: StoryBranchProps) {
  const nodes = useMemo(() => buildTree(messages, rawMessages), [messages, rawMessages]);

  if (nodes.length === 0) {
    return (
      <div className="flex flex-col items-center py-8 text-gray-400">
        <svg className="w-10 h-10 mb-2 opacity-40" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25H12" />
        </svg>
        <p className="text-sm">剧情分支还没长出来</p>
      </div>
    );
  }

  return (
    <div className="relative pl-6">
      {/* Vertical line */}
      <div className="absolute left-[11px] top-2 bottom-2 w-0.5 bg-gray-200" />

      {nodes.map((node) => (
        <div key={node.id} className="relative mb-1">
          {node.type === 'narration' ? (
            /* Narration node */
            <div className="flex items-start gap-3 group">
              <div className="relative z-10 mt-1.5 w-2.5 h-2.5 rounded-full bg-gray-300 border-2 border-white shrink-0" />
              <button
                onClick={() => node.messageIndex >= 0 && onNodeClick?.(node.messageIndex)}
                className="text-left text-xs text-gray-500 leading-relaxed py-1 hover:text-gray-700 transition-colors cursor-pointer"
              >
                {truncate(node.content)}
              </button>
            </div>
          ) : (
            /* Choice branch point */
            <div className="ml-0">
              {/* Selected choice */}
              <div className="flex items-start gap-3 group">
                <div className="relative z-10 mt-1 w-3 h-3 rounded-full bg-[var(--color-brand,#3b82c4)] border-2 border-white shrink-0" />
                <button
                  onClick={() => node.messageIndex >= 0 && onNodeClick?.(node.messageIndex)}
                  className="text-left text-xs font-medium text-[var(--color-brand,#3b82c4)] leading-relaxed py-1 hover:opacity-80 transition-opacity cursor-pointer"
                >
                  选择：{truncate(node.content)}
                  <span className="ml-1.5 text-[10px] text-[var(--color-brand,#3b82c4)]/60">← 你当时走了这条</span>
                </button>
              </div>

              {/* Unexplored branches */}
              {node.children.length > 0 && (
                <div className="ml-3 mt-0.5 mb-1">
                  {node.children.map((child) => (
                    <div key={child.id} className="flex items-start gap-3 relative">
                      {/* Branch connector */}
                      <div className="relative z-10 mt-1.5 shrink-0">
                        <svg className="w-4 h-3 text-gray-300" viewBox="0 0 16 12" fill="none">
                          <path d="M0 0 L8 0 L8 6 L16 6" stroke="currentColor" strokeWidth="1.5" fill="none" />
                        </svg>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <div className="w-2 h-2 rounded-full bg-gray-200 border border-gray-300 shrink-0" />
                        <span className="text-[11px] text-gray-400 leading-relaxed py-0.5">
                          选择：{truncate(child.content)}
                          <span className="ml-1 text-[10px] text-gray-300">(你还没走到这条线)</span>
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
